### PR TITLE
rust 1.61.0

### PR DESCRIPTION
**Pull request by mlilien**

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by mlilien** [comment]
> How this has been tested?

I tested it with dunfell 3.1.17 and a rust project which makes use of rust 1.61 linking modifier syntax.

**Review by kraj — APPROVED** [review]
lgtm

**Comment by mlilien** [comment]
@kraj Thanks for approving. How do we continue? The check didn't find a worker. Can you merge it anyway?

**Comment by mlilien** [comment]
> Hello, just to let you know, this pull request will not work with Kirkstone and we will need another commit to fix it when kirkstone version is merged. By reason: Yocto Kirkstone provides another version of Cargo and Rust. In "Cargo_1.61.0.bb", if u do a require "recipes-devtools/rust/rust-source.inc", because these two files are not in the same repository, the "require" will find this rust-source.inc in poky (with BBPATH) and we will have a conflict. (the Kirstone version of Cargo and Rust is 1.59). I propose a very simple solution, what you need to do it's actually add "rust-source-1.61.0.inc" and "rust-snapshot-1.61.inc", and in the cargo*.bb file of version 1.61.0 in "Cargo", u add an "-{PV}" after the filenames in "require".
> 
> Thanks

This PR doesn't add kirkstone to `LAYERSERIES_COMPAT_rust-layer` anyway.

**Comment by ElD4n1** [comment]
> > Hello, just to let you know, this pull request will not work with Kirkstone and we will need another commit to fix it when kirkstone version is merged. By reason: Yocto Kirkstone provides another version of Cargo and Rust. In "Cargo_1.61.0.bb", if u do a require "recipes-devtools/rust/rust-source.inc", because these two files are not in the same repository, the "require" will find this rust-source.inc in poky (with BBPATH) and we will have a conflict. (the Kirstone version of Cargo and Rust is 1.59). I propose a very simple solution, what you need to do it's actually add "rust-source-1.61.0.inc" and "rust-snapshot-1.61.inc", and in the cargo*.bb file of version 1.61.0 in "Cargo", u add an "-{PV}" after the filenames in "require".
> > Thanks
> 
> This PR doesn't add kirkstone to `LAYERSERIES_COMPAT_rust-layer` anyway.
> 
> You could solve your dependency conflict by masking:
> 
> ```
> BBMASK .= " /poky/meta/recipes-devtools/rust/ "
> BBMASK .= " /poky/meta/recipes-devtools/cargo/ "
> RUSTVERSION = "1.61%"
> ```

I also needed to put the `meta-rust` layer before the `poky/meta` layer in `bblayers.conf`, because `BBMASK` seems to only mask .bb and .bbappend files and not .inc files ([BBMASK doc](https://docs.yoctoproject.org/ref-manual/variables.html#term-BBMASK)).

**Comment by srwalter** [comment]
@mlilien please rebase your branch so that hopefully the CI will pass.  Thanks!

**Review by srwalter — APPROVED** [review]

**Pull request merged**
