### PR TITLE
Further simplify LIC_FILES_CHKSUM

### PR DESCRIPTION
**Pull request by shr-project**
Tested with bitbake -e:
```
$ grep ^LICENSE= env.*
env.cargo:LICENSE="MIT | Apache-2.0"
env.cargo.new:LICENSE="MIT | Apache-2.0"
env.cargo.new.1.37.0:LICENSE="MIT | Apache-2.0"
env.rust-llvm:LICENSE="Apache-2.0-with-LLVM-exception"
env.rust-llvm.new:LICENSE="Apache-2.0-with-LLVM-exception"
env.rust-llvm.new.1.37.0:LICENSE="NCSA"

$ grep ^LIC_FILES_CHKSUM= env.*
env.cargo:LIC_FILES_CHKSUM="     file://LICENSE-MIT;md5=b377b220f43d747efdec40d69fcaa69d       file://LICENSE-APACHE;md5=71b224ca933f0676e26d5c2e2271331c     file://LICENSE-THIRD-PARTY;md5=f257ad009884cb88a3a87d6920e7180a "
env.cargo.new:LIC_FILES_CHKSUM="     file://LICENSE-MIT;md5=b377b220f43d747efdec40d69fcaa69d       file://LICENSE-APACHE;md5=71b224ca933f0676e26d5c2e2271331c     file://LICENSE-THIRD-PARTY;md5=f257ad009884cb88a3a87d6920e7180a "
env.cargo.new.1.37.0:LIC_FILES_CHKSUM="     file://LICENSE-MIT;md5=b377b220f43d747efdec40d69fcaa69d       file://LICENSE-APACHE;md5=71b224ca933f0676e26d5c2e2271331c     file://LICENSE-THIRD-PARTY;md5=f257ad009884cb88a3a87d6920e7180a "
env.rust-llvm:LIC_FILES_CHKSUM="file://LICENSE.TXT;md5=8a15a0759ef07f2682d2ba4b893c9afe"
env.rust-llvm.new:LIC_FILES_CHKSUM="file://LICENSE.TXT;md5=8a15a0759ef07f2682d2ba4b893c9afe"
env.rust-llvm.new.1.37.0:LIC_FILES_CHKSUM="file://LICENSE.TXT;md5=c6b766a4e85dd28301eeed54a6684648"

$ grep ^PV= env.*
env.cargo:PV="1.47.0"
env.cargo.new:PV="1.47.0"
env.cargo.new.1.37.0:PV="1.37.0"
env.rust-llvm:PV="1.47.0"
env.rust-llvm.new:PV="1.47.0"
env.rust-llvm.new.1.37.0:PV="1.37.0"
```

If

### CODE REVIEW

**Comment by shr-project** [comment]
@jmesmon thanks for quick merge of #297 

This is small follow up cleanup if you prefer this direction.

**Comment by jmesmon** [comment]
I'm in favor of this. Seems like a good reduction. Add me as a reviewer when you change it from a draft to a pr 👍

**Comment by shr-project** [comment]
@jmesmon I think I'm done with cleanups now :).

**Review by jmesmon — APPROVED** [review]
This looks great, thanks. The rust_versions.inc will definitely be helpful for us to test the older versions (just need to get a ci setup that works going again 😭 )

**Pull request merged**
