### PR TITLE
bump to Rust 1.15.1

### PR DESCRIPTION
**Pull request by cardoe**

### CODE REVIEW

**Comment by jmesmon** [comment]
Just a note: the patch "mk: for stage0, use RUSTFLAGS to override target libs dir" was, IIRC, only needed due to our previous use of a special libdir/bindir for cross compilers. It should be possible to just drop that patch entirely (if there is a desire to do so).

With the new rustbuild system replacing make, it will likely be gone soon anyhow.

**Comment by cardoe** [comment]
Thanks @jmesmon. I still need to look into your Gentoo Rust issue as well.

**Comment by cajun-rat** [comment]
rust-1.15 would be mighty useful for some stuff that we are working on--is there a major problem that is stopping this, or can I help somehow to get this PR in?

**Comment by derekstraka** [comment]
I believe I left it with a single recipe needing to be converted.  @cardoe may have more specifics

**Comment by cardoe** [comment]
@cajun-rat The issue was in building libstd-rs. Its wanting depends that aren't being satisfied and I can't figure out why.

**Comment by cardoe** [comment]
Local build on x86_64 for x86_64 has worked. CI still needs to churn over the remaining bits but I think this is ready for some feedback.

**Comment by cardoe** [comment]
@cajun-rat Feel free to kick the tires

**Comment by cardoe** [comment]
oh fwiw, this is the last version I plan on backporting to morty.

**Comment by cajun-rat** [comment]
Nice, thank you!  We're using Morty at the moment: I tried a dumb attempt to merge this into the morty branch of meta-rust, but there were some merge conflicts I couldn't see the answer to without more knowledge. I made some guesses, but the resultant code didn't work :).

**Pull request merged**
