### PR TITLE
rust: Enable ppc64le target

### PR DESCRIPTION
**Pull request by kraj**
this helps building the compiler, work is still needed for libstd-rs and
other pieces

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Review by tylerwhall — APPROVED** [review]
The vector alignments aren't included in `--print target-spec-json` for `powerpc64le-unknown-linux-gnu`. Curious when those are required and how they're derived. Seems reasonable and harmless though.

`v256:256:256-v512:512:512`

**Comment by kraj** [comment]
> The vector alignments aren't included in `--print target-spec-json` for `powerpc64le-unknown-linux-gnu`. Curious when those are required and how they're derived. Seems reasonable and harmless though.
> 
> `v256:256:256-v512:512:512`

I have take them from llvm sources 

https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGen/target-data.c#L153-L155

**Comment by ColinFinck** [comment]
Please also check https://github.com/meta-rust/meta-rust/pull/319, where I did a ppc64-specific change.

**Comment by kraj** [comment]
can we merge this

**Pull request merged**
