### PR TITLE
getVar will expand by default, so the 'True' option is no longer required

### PR DESCRIPTION
**Pull request by derekstraka**

### CODE REVIEW

**Comment by cardoe** [comment]
What version of Yocto does this begin the default?

--
Doug

**Comment by derekstraka** [comment]
It is only in [master](https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=2631c375b8a025ee2e4329f6d93900bb7b5dadf7)

**Comment by derekstraka** [comment]
This needs to be merged after the morty branch is created

**Comment by derekstraka** [comment]
The build will be broken until we switch back to master as the default

**Pull request merged**
