### PR TITLE
Import Rust 1.58.1 from openembedded-core, remove Rust 1.51.0

### PR DESCRIPTION
**Pull request by ColinFinck**
As I found out and wrote in https://github.com/meta-rust/meta-rust/pull/364#issuecomment-1016643903, meta-openembedded has no plans to backport their Rust support to LTS releases like dunfell.
However, I have always used the latest Rust version via meta-rust on dunfell and want to continue doing so.

This Rust 1.58.1 import to meta-rust is meant for dunfell and every other Yocto release where oe-core doesn't provide a Rust version or has no interest in backporting the latest Rust version.

### CODE REVIEW

**Comment by M1cha** [comment]
This doesn't work on dunfell because it's version of bitbake doesn't support `:` for variables.
After replacing all `:` with `_` it works just fine though.

**Comment by otavio** [comment]
Dunfell supports it; you're likely using an old dunfell release.

**Comment by ColinFinck** [comment]
For the record, I'm using this branch successfully on an embedded system running latest Yocto Dunfell.

**Comment by janderholm** [comment]
We are fine with using the version from meta-openembedded, and Dunfell isn't important either!

**Review by kraj — APPROVED** [review]
lgtm

**Comment by kraj** [comment]
> @danc86 @janderholm @kraj @srwalter Is anyone of you still interested in having this repo for modern Rust support in Dunfell? (and other Yocto releases where meta-openembedded doesn't provide latest Rust)
> 
> It feels like many people have moved over to meta-openembedded's Rust support. But I will be with the Dunfell LTS release for a while, and probably some other people as well. I need at least one review to merge this.

I think its valuable for dunfell releases. So I am fine with this patch

**Comment by ColinFinck** [comment]
@kraj Thanks for the approval!

@otavio meta-openembedded doesn't want to backport Rust feature releases from their `master` branch to the release branches.
As such, when a new Yocto LTS is out, it will get a single Rust version and then only "fixes" and "security patches", but no upgrades to new Rust releases.
Sounds to me like this meta-rust repo will be relevant for much longer.

**Pull request merged**
