### PR TITLE
workflows: Refactor yml to improve build time

### PR DESCRIPTION
**Pull request by weltling**
- Split out the build configuration job
- Use the official sstate mirror
<strike>- Disable more of unnecessary features</strike>

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>

### CODE REVIEW

**Comment by weltling** [comment]
Hmm, looks like this is the fastest run and not reducing the build doesn't cause storage overflow issues. I'd guess the official `sstate` is picked up, so this approach might indeed serve. Switching to fixed poky release tags will be needed, however.

Thanks.

**Review by srwalter — APPROVED** [review]

**Comment by srwalter** [comment]
@jmesmon I noticed "squash and merge" is disabled in this project.  I'm not sure who changed it, do you have an opinion on its use?

**Comment by jmesmon** [comment]
I'm unopposed to enabling/allowing it 🤷‍♂️

It's nice sometimes to have that option so folks don't need to locally squash.

**Comment by weltling** [comment]
Thanks for the checks!

A case having to push incremental changes to satisfy CI is always about piling an onion. Requiring to squash the original change set would be certainly justified in such a case.

Generalizing might be good enough, too. Requiring to merge just one commit (and description) could be more conceptive. Still it's up to whether on would like to keep the history.

Thanks

**Pull request merged**
