### PR TITLE
Update to Rust 1.51.0

### PR DESCRIPTION
**Pull request by ColinFinck**
Same procedure as every few months :)

I didn't add the RISC-V patches from @kraj as it looks like all of them have made it upstream.
Please add back anything that is missing.

### CODE REVIEW

**Comment by kraj** [comment]
Please squash both commits into single commit

**Comment by ColinFinck** [comment]
> Please squash both commits into single commit,
> secondly also delete 1.47 recipe along with this pull.

Done

**Review by kraj — COMMENTED** [review]
looks ok to me. I am running a riscv/musl build with this pull here and lets see what happens.

**Review by kraj — APPROVED** [review]
works as expected on rv32/glibc

**Comment by kraj** [comment]
the musl/riscv patches are still needed. I have forward ported them here

**Review by otavio — APPROVED** [review]

**Comment by kraj** [comment]
@ColinFinck please cherry-pick https://github.com/YoeDistro/meta-rust/commit/53ae963a095ae90706cdacf83bd76b4278c49e40 on top of this pull so we can get riscv/musl also taken care

**Comment by kraj** [comment]
i have included thid patch in https://github.com/meta-rust/meta-rust/pull/330 so lets close this and review it there

**Comment by ColinFinck** [comment]
Superseded by #330

**Pull request closed without merging**
