### PR TITLE
add proxies to the rust and cargo compilation

### PR DESCRIPTION
**Pull request by tardyp**
Note that this does not help build reproduceability to get stuff in the compile phase

### CODE REVIEW

**Comment by derekstraka** [comment]
Is there a reason the items aren't pulled during the do_fetch phase?  Could you provide a little bit more on the errors you were encountering (obviously a proxy error but what is it trying to pull down)?

**Comment by tardyp** [comment]
This happens when I build the genivi platform:

```
determined most recent snapshot: rust-stage0-2015-12-18-3391630-linux-x86_64-97e2a5eb8904962df8596e95d6e5d9b574d73bf4.tar.bz2
Traceback (most recent call last):
  File "/data/genivi/genivi-dev-platform/gdp-src-build/tmp/work-shared/rust-1.7.0-r0/rustc-1.7.0/src/etc/get-snapshot.py", line 78, in <module>
    main(sys.argv)
  File "/data/genivi/genivi-dev-platform/gdp-src-build/tmp/work-shared/rust-1.7.0-r0/rustc-1.7.0/src/etc/get-snapshot.py", line 66, in main
    get_url_to_file(url, dl)
  File "/data/genivi/genivi-dev-platform/gdp-src-build/tmp/work-shared/rust-1.7.0-r0/rustc-1.7.0/src/etc/snapshot.py", line 163, in get_url_to_file
    raise Exception("failed to fetch url")
Exception: failed to fetch url
make: *** [x86_64-linux/stage0/bin/rustc] Error 1
ERROR: oe_runmake failed
ERROR: Function failed: do_compile (log file is located at /data/genivi/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/rust-cross-x86_64/1.7.0-r0/temp/log.do_compile.23463)
```
on a cargo recipe:
```
DEBUG: Executing shell function do_compile
/data/genivi/genivi-dev-platform/gdp-src-build/tmp/sysroots/x86_64-linux/usr/bin/cargo
/data/genivi/genivi-dev-platform/gdp-src-build/tmp/sysroots/x86_64-linux/usr/bin/x86_64-poky-linux/rustc
NOTE: cargo build -v --target x86_64-poky-linux --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update registry https://github.com/rust-lang/crates.io-index

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [2/-1] Failed to connect to github.com: Connection timed out
WARNING: exit code 101 from a shell command.
ERROR: Function failed: do_compile (log file is located at /data/genivi/genivi-dev-platform/gdp-src-build/tmp/work/core2-64-poky-linux/rvi-sota-client/git-r0/temp/log.do_compile.32504)
```

on cargo build itself:
```
DEBUG: Executing shell function do_compile
NOTE: make -j 8 ARGS=--verbose
/data/genivi/genivi-dev-platform/gdp-src-build/tmp/sysroots/x86_64-linux/usr/bin/rustc -V
rustc 1.7.0-dev
target/snapshot/bin/cargo --version
cargo 0.9.0-nightly (c4c6f39 2016-01-30)
target/snapshot/bin/cargo build --target x86_64-linux --release  --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [2/-1] Failed to connect to github.com: Connection timed out
make: *** [cargo-x86_64-linux] Error 101
ERROR: oe_runmake failed
ERROR: Function failed: do_compile (log file is located at /data/genivi/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/cargo-native/0.9.0-r0/temp/log.do_compile.28916)
```

**Comment by derekstraka** [comment]
Thanks for the info.  I want to make sure we apply this to the appropriate place.  Are you using the jethro or krogoth branch (master is on rust-1.10)?

**Comment by tardyp** [comment]
genivi points to 395cde5 which looks like visible from master branch only

looks like rust 1.7

I tried to update to tip of master, but it will not build, as requiring some new packages

**Comment by cardoe** [comment]
Any chance you can test with the krogoth branch?

**Comment by cardoe** [comment]
@tardyp I think you're actually seeing the same issue as #84.

**Comment by cardoe** [comment]
These changes are just patently wrong. Its because the recipes in question are not using the meta-rust layer properly and not specifying their dependencies in the recipe causing Cargo to attempt to download them during the build phase since we haven't downloaded them before hand. Since we do not have the ability to tell Cargo do not attempt to fetch missing dependencies this is why that's happening.

**Pull request closed without merging**
